%{
#include <iostream>

int yylex();
int yyerror(const char *p) { std::cerr << "error: " << p << std::endl; };
%}

%start bin_num

%type <val> bin_num digit

%%

bin_num: digit+;

digit: '0' | '1';

%%

int main()
{
    yyparse(); // A parsing function that will be generated by Bison.
    return 0;
}
