%{
#include <iostream>

int yylex();
int yyerror(const char *p) { std::cerr << "error: " << p << std::endl; };
%}

%start assign

%type <val> assign identifier float digit letter

%%

assign: "float" identifier '=' float ';';

identifier: (letter||'_')(digit||letter||'_')+;

float: ['-'||'+'] digit+ [('.'digit+)];

digit: '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';

letter: 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g';

%%

int main()
{
    yyparse(); // A parsing function that will be generated by Bison.
    return 0;
}
