name: Package

on: [push]

env:
  NET_ID: ${{ secrets.NET_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        bison --version
        flex --version
        ./make.sh

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        ./run.sh examples/cal1.y
        ./run.sh examples/cal2.y
        ./run.sh examples/test1.y
        ./run.sh examples/test2.y
        ./run.sh examples/test4.y
        ./run.sh examples/tinybasic.in

    - name: Package
      working-directory: ${{github.workspace}}
      run: |
        ./package.sh "$NET_ID"
        (cd dist/package; zip -r ../../package.zip .)

    - name: Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: 
          package.zip
